severity: Warning        # severity for «root» logger
fight:                    # logger named «node»
    severity: Debug      # severity for logger «node»
    file: fight.log  # messages for «node» will be sent to skovoroda.log
                         # messages won't be printed to any file
